[DONE]Feature multiple repo
WalkingMachine/sara_install pull request #10
Opened 2016-10-25 04:09 UTC by gortium

Merger en meme temps que les branch du meme nom dans les autre repo

2016-10-25 04:14 UTC, gregoirefra requested changes
Please see my comment in the file changed

2016-10-25 04:14 UTC, gregoirefra commented on script/sara_simulation_installer.bash
> +sudo apt install -y ros-indigo-desktop-full -y
This wont work since the setup will be done on a server without a GUI

2016-10-25 04:14 UTC, gregoirefra commented on script/sara_simulation_installer.bash
> +catkin_make -DCATKIN_WHITELIST_PACKAGES="wm_arm_msgs"
Wasn't there a fix for this? I believe @maximest-pierre had solved the issue

2016-10-25 04:15 UTC, maximeconnolly commented
This was fix by me. We dont need the horrible hack to build.

2016-10-25 04:23 UTC, gortium commented
On witch branch ? i took master to start these.. merge and refix i guess?

2016-10-25 05:01 UTC, maximest-pierre commented
It suppose to be fix in master cause i just build master recently and there is not need for it

2016-10-25 13:59 UTC, gregoirefra commented
Merger et fixer après n'est vraiment pas une bonne pratique quand le problème a déjà été résolu. Essai de merge master dans ta branch en premier pour bien voir les changements

2016-10-25 14:10 UTC, gortium commented
Mais.. Regarde le graph dans l'onglet network.. Ma branch part du dernier commit sur master alors je comprend pas pourquoi j'aurais pas les changes..

2016-10-25 14:13 UTC, gregoirefra commented
@maximest-pierre peux-tu confirmer que tu as bien commit t'es changements parce qu'effectivement c'est la même chose que dans master qu'il a mais je suis quasi certain que tu avais changé cette partie

2016-10-25 15:10 UTC, maximest-pierre commented
Ses merger dans master de sara_commun.

2016-10-25 15:12 UTC, gregoirefra commented
Euh quoi? Peux-tu commit le changement ici aussi alors?

2016-10-25 15:15 UTC, gortium commented
Haaaa ok il parle du scrip de travis... Pas la meme chose... hmm faut trouver un moyen de sync les deux 0o

2016-10-26 04:01 UTC, gregoirefra commented
Après validation il n'est pas necessaire de faire un catkin_make avec whitelist mais seulement un catkin_make et tout fonctionne sauf que présentement le script me donne une erreur que catkin_make n'est pas trouvé dans l'environement, toute fois en testant j'ai trouvé que si tu source ton ~/.bashrc et ensuite catkin_make, le tout dans un autre script tu es correct et ca build sans problème

2016-10-26 14:32 UTC, gortium commented
Hmm mais le truc c'est que c'est pas des changes/bugfix qui devrait avoir rapport avec ma branch non?

2016-10-27 18:57 UTC, gregoirefra approved these changes

2016-10-28 04:17 UTC, merged