Remove extra file
WalkingMachine/sara_install pull request #24
Opened 2017-03-22 04:10 UTC by maximest-pierre

The file were remove because they are extra.

The correct .rosinstall is in a different repo

I also remove the extra script that was to build ros from source.

2017-03-22 18:23 UTC, gregoirefra requested changes

2017-03-22 18:23 UTC, gregoirefra commented on script/install_sara_packages.bash
> +wget https://raw.githubusercontent.com/WalkingMachine/ros_install/master/desktop.rosinstall
Ce lien est inexistant

2017-03-22 18:23 UTC, gregoirefra commented on script/install_sara_robot_packages.bash
> +wget https://raw.githubusercontent.com/WalkingMachine/ros_install/master/sara.rosinstall
Ce lien n'existe pas

2017-03-22 18:23 UTC, gregoirefra commented on script/install_sara_robot_packages.bash
> +rosdep update
On ne peut ce fier que sur ceci car ce c'est pas tout les packages qui ont les bonne dépendances dans leur package. Ils faut ajouter manuellement les apt-get install requis svp

2017-03-23 16:25 UTC, maximest-pierre commented
![screenshot from 2017-03-23 12-23-09](https://cloud.githubusercontent.com/assets/7928135/24258275/9edde474-0fc3-11e7-8cc8-bb220f90ad61.png)
 This pr is related to a pr on the ros_install repo

2018-06-02 04:54 UTC, closed without merging