correct the rosdep problem
WalkingMachine/sara_install pull request #3
Opened 2016-09-20 17:11 UTC by salco

I try but i'm not sure if it's ok. tell me if I need to change anyting.

2016-09-20 17:32 UTC, maximeconnolly requested changes
The $USER variable returns root or runuser not the current login user.

2016-09-20 20:28 UTC, salco commented
J'ai deux commande possible, 
choix 1: runuser -l $SUDO_USER -c "la_commande_ici"
choix 2: sudo -H -u $SUDO_USER bash -c 'la_commande_ici'

Jai comparer les deux avec "printenv" et je crois que le deuxieme est un meilleur choix.

2016-09-20 21:31 UTC, maximest-pierre commented
Le choix numero 2

2016-09-23 19:01 UTC, salco commented
Voila, je vien de finir l'installeur est ce que ca passe au vote?

2016-09-26 14:15 UTC, gregoirefra reviewed
Hmm je suis pas convaincu de l'utilité du `-H -u $SUDO_USER bash -c`
Moi j'opterais juste pour `sudo [la commande]` étant donné que la tu demande à `sudo` un changement de home directory et de user qui roule la commande ce qui te force à faire un `chown` à la fin du script. Il faudrait le tester mais je suis presque sur que si tu fais juste `sudo` tu aura pas de `chow` à faire par la suite et que tu n'aura pas à changer le home du user qui roule la commande.

2016-09-26 15:34 UTC, salco commented
le `chown` est seulement par protection il peut sûrement être améliorer le `-H` peut sûrement être enlever.
La dernière version envoyer je l'ai tester et tout fonctionne. l’idée étant de ne pas mettre de sudo "root" partout dans le `bash` sans avertir le user, de cette façon la le seul moyen de rouler le bash est avec les droit root et de plus plusieurs check-up son fait dans cette version.

2016-09-26 15:37 UTC, salco commented
lutilisation du sudo pour retourner en mode user est seulement une patch éventuellement une meilleur implémentation pourrai être fait pour le faire en 2 partie 1 installation et l’autre la compilation.

2016-10-25 16:26 UTC, gortium commented
@salco If you could put your change on a branch of this repository please, and not a fork. It will be easier too work with it.

2017-03-22 18:18 UTC, gregoirefra commented
Source repo doesnt exist any more so this will be closed

2017-03-22 18:18 UTC, closed without merging